### ISSUE TITLE
Leaders unable to view rosters

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#128]
I've had two separate leaders reach out to me not being able to view the rosters for the people who've signed up for their group. This is one such message:

"Hey ladies, when I login to manage my group, this is all I see. It says I have 4 people but I've only gotten 3 email notifications so I'm not sure who my 4th person is and it's not showing my ladies either."

![img_2359](https://cloud.githubusercontent.com/assets/26365037/25391370/195b7302-29a4-11e7-8916-a408ffd52292.JPG)

**Comment by jeffklassen** [comment]
@amandawmosaic As noted in my

**Comment by jeffklassen** [comment]
@amandawmosaic Is this still a problem? Has @pblair12 or @BKreisel been able to take a look at it if not?

**Comment by pblair12** [comment]
ah no sorry I didn't look into it

**Comment by BKreisel** [comment]
I've been unable to replicate the issue. @amandawmosaic do you know the name of the group that was having problems?

**Comment by amandawmosaic** [comment]
Checking now.

**Comment by amandawmosaic** [comment]
This isn't a problem anymore. Thanks!
