### ISSUE TITLE
Group Create Erroring out

### ISSUE THREAD

**Issue by BKreisel** [MosaicGroups/mosaic-groups#131]
Got the messages below while trying to create a student group. I was left on the form page with the following console errors. The group did actually get created though.

`index.js:1 Uncaught TypeError: Cannot read property 'length' of undefined
    at groupIsFull (webpack:///./client/src/App/utils/index.js?:1:227)
    at ActionLinks (webpack:///./client/src/App/components/groups/list/ActionLinks.jsx?:27:315)`

and

`request-base.js:27 Uncaught TypeError: fulfill is not a function`

**Comment by jeffklassen** [comment]
GREAT catch, @BKreisel. I've fixed this in the group-join branch that we are working on merging now.
