### ISSUE TITLE
Admin Settings Manipulation

### ISSUE THREAD

**Issue by jeffklassen** [MosaicGroups/mosaic-groups#136]
The admin settings manipulation well needs to be completed:

<img width="451" alt="screen shot 2017-05-04 at 6 47 57 am" src="https://cloud.githubusercontent.com/assets/7376576/25690996/1272aab6-3097-11e7-8c30-8275d822cb93.png">

**Comment by jeffklassen** [comment]
@BKreisel have you made any progress on this? Are you going to be able to early this week? If not, I'd like to knock it out.

**Comment by jeffklassen** [comment]
Check out the very little bit of the admin panel I started in this branch: https://github.com/MosaicGroups/mosaic-groups/tree/admin-settings-well

If you want to work on this and have already done this, please feel free to discard my work.

**Comment by BKreisel** [comment]
I did start it but I had only implemented just about as much as you did. You'll get it done much quicker than I will. Go for it.

**Comment by jeffklassen** [comment]
@BKreisel Work has gotten really intense through Monday. Can you take this over? I have my latest work checked in and pushed.

**Comment by jeffklassen** [comment]
With @BKreisel 's help, I've completed the admin settings well. The next step to close this is to make sure all settings are properly reflected on other parts of the page.

**Comment by jeffklassen** [comment]
Done!
