### ISSUE TITLE
Hide group once full (High Priority)

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#139]
Can we remove a group from the public display once it's filled? 

If it's possible to accomplish this before the weekend I will award 10 points to Gryffindor.

**Comment by jeffklassen** [comment]
@amandawmosaic do we want people to be completely unable to view full groups, or do we want to just clean up the ui?

A simple way to handle this would be for me to set the hide full groups check box to checked, but then of course the user could uncheck the box:

<img width="339" alt="screen shot 2017-05-04 at 4 27 28 pm" src="https://cloud.githubusercontent.com/assets/7376576/25708413/ba6114ac-30e6-11e7-8d96-97787f2af11b.png">

**Comment by amandawmosaic** [comment]
I don't want anyone to be able to see a group once it's filled ever. We have wait lists stacking up, and it's preventing people from getting into other groups.

**Comment by jeffklassen** [comment]
Do you want to be able to see full groups, or do you fall into the 'anyone'
who should ever see full groups ever?

**Comment by amandawmosaic** [comment]
Nope, I'm special. I'd like myself and Jess to still be able to see them if possible.

**Comment by jeffklassen** [comment]
Okay can do. Can we just hide them from the UI? The implications of this
being that a hacker could view full groups, but they wont be shown on the
page to anyone but admins.

Does that sound good?

**Comment by amandawmosaic** [comment]
Sounds great.

**Comment by jeffklassen** [comment]
I've fixed this -- PLEASE go into the app ASAP and make sure everything
works exactly how you think it should (by logging in, and making sure you
see the groups you want to see and then logging out and making sure you see
the groups you want to see.

**Comment by amandawmosaic** [comment]
OK the UI looks awesome. Here's the one thing I didn't account for. Group leaders need to be able to see their groups when they login to pull information and make changes to their rosters. 

Can you make it so anyone with a login can see the full groups when they're logged in?
