### ISSUE TITLE
Alter "Group Is Filled" Message [Also High Priority]

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#140]
Please replace the message that appears when you click "this group is full" link with the message below excluding the leader's email.

"Looks Like This Group is Full!"

This is most likely because the leader is meeting in their home and has a limited amount of space.

It may also be that the leader wants to create an environment for vulnerability and too large a group would prevent that.

Don't worry though, we have plenty of other groups available that will definitely make it possible for you to get connected here at Mosaic.”

**Comment by jeffklassen** [comment]
I thought we were hiding full groups?

**Comment by amandawmosaic** [comment]
Woooowww. Yeah we are. Disregard.
