### ISSUE TITLE
No indication of required fields

### ISSUE THREAD

**Issue by mnmercer** [MosaicGroups/mosaic-groups#153]
In the form to a create group, there is no indication of which fields are required. The only way to determine which fields are required is to keep clicking the submit button and filling out the fields it tells you to. 
<img width="1147" alt="screen shot 2017-05-07 at 2 55 30 pm" src="https://cloud.githubusercontent.com/assets/9361260/25784086/e408c3ee-3335-11e7-8711-9c05ab9f1e53.png">
![screen shot 2017-05-07 at 2 57 54 pm](https://cloud.githubusercontent.com/assets/9361260/25784088/e575a49a-3335-11e7-84dd-737a37c4c36d.png)

**Comment by jeffklassen** [comment]
@mnmercer want to take this one?

**Comment by mnmercer** [comment]
@jeffklassen I can definitely take this. I'll look into it this evening.

**Comment by jeffklassen** [comment]
Thanks for working on this @mnmercer. Do you view that latest PR #166 as fixing this? Can we close this?

**Comment by mnmercer** [comment]
@jeffklassen Yes it does. According to new UX research, marking the optional fields instead of the required fields leads to more information being filled out.

**Comment by jeffklassen** [comment]
VERY Nice!!! I like UX but dont know a ton about it. Thanks for keeping us
straight
