### ISSUE TITLE
Site not working with Firefox?

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#158]
Hey guys, I received this email

_"Amanda.  One thing I have noticed is that the growth groups website doesn’t work for me if I’m using IU or Firefox browsers.  It only works when using Chrome.  I don’t know if that’s happening for others, but probably worth looking into."_

Are we able to determine if this is an issue for all Firefox users or if it's just user error?

**Comment by mnmercer** [comment]
@amandawmosaic In order to investigate it, it would be good to have some clarification. What do they mean by "not working"? Does the site load? I'm not finding any issues briefly playing around with it myself.

**Comment by amandawmosaic** [comment]
I’ll find out
A M A N D A   W E I K E L
GROUPS & STUDENT DIRECTOR
757-515-0705 <tel:+757-515-0705>
www.mosaicchristian.org <http://www.mosaicchristian.org/>

**Comment by jeffklassen** [comment]
@amandawmosaic closing this since there has not been an update. Please feel free to reopen if you discover this is still a problem
