### ISSUE TITLE
Suggestion: Modal should close when background is clicked

### ISSUE THREAD

**Issue by pblair12** [MosaicGroups/mosaic-groups#169]
When the modal opens after the user presses the 'Host', 'Lead', or 'Childcare' buttons I think that the modal should close when the user clicks on the background that is outside of the modal (as well as when they click on the OK button).

This is just a suggestion, not a bug.

**Comment by jeffklassen** [comment]
@pblair12 I couldn't agree with you more.

**Comment by jeffklassen** [comment]
Done!
