### ISSUE TITLE
Day Filter Does Not Reset

### ISSUE THREAD

**Issue by mnmercer** [MosaicGroups/mosaic-groups#170]
After selecting a value in the Day filter on the main page, that value is stuck in the field even if you select another day or unselect all of them.
<img width="410" alt="screen shot 2017-05-18 at 8 46 04 am" src="https://cloud.githubusercontent.com/assets/9361260/26202815/c0e51a42-3ba6-11e7-8327-636a184a9e93.png">

**Comment by jeffklassen** [comment]
@mnmercer I cant reproduce this one (and I've tried across multiple browsers and app states). What browser are you using?

**Comment by mnmercer** [comment]
I was using Chrome at the time. I can't seem to reproduce it either. Looks like it fixed itself?

**Comment by jeffklassen** [comment]
Thanks for checking and confirming. It's never fun when an issue can't be
reproduced. Let's close this for now and reopen if we spot it again

**Comment by mnmercer** [comment]
Fair enough.
