### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by mnmercer** [MosaicGroups/mosaic-groups#171]
On opening the site, I get this error in the JavaScript console.
<img width="1096" alt="screen shot 2017-05-18 at 10 08 20 am" src="https://cloud.githubusercontent.com/assets/9361260/26206164/0a34694a-3bb2-11e7-8064-30d008046942.png">

**Comment by jeffklassen** [comment]
Please include steps to reproduce

**Comment by mnmercer** [comment]
@jeffklassen 
Steps to reproduce:

1. Open https://mosaicgroups-dev.herokuapp.com/ or start up a running local instance on the `react-dev` branch.

**Comment by jeffklassen** [comment]
Ah! I see. If you build with webpack-watch, do you get a better stacktrace?

**Comment by mnmercer** [comment]
Yeah. Now the Chrome error looks like this.
<img width="1087" alt="screen shot 2017-05-18 at 11 47 18 am" src="https://cloud.githubusercontent.com/assets/9361260/26211149/cfb92590-3bbf-11e7-9fba-19cd169d54da.png">
The Firefox error looks like this. I couldn't capture the entire stack trace, but I think this will be informative enough.
<img width="1679" alt="screen shot 2017-05-18 at 11 48 46 am" src="https://cloud.githubusercontent.com/assets/9361260/26211206/040442ee-3bc0-11e7-983d-3943dd7100e0.png">

**Comment by jeffklassen** [comment]
That's great! Looks like we just need to check if(identity.roles &&
identity.roles includes....

**Comment by jeffklassen** [comment]
@mnmercer Man - i can't reproduce the error: 

<img width="458" alt="screen shot 2017-05-19 at 12 44 14 pm" src="https://cloud.githubusercontent.com/assets/7376576/26244657/ed271250-3c90-11e7-8486-643d882967f7.png">

**Comment by jeffklassen** [comment]
Never mind, I just duplicated it. It looks like you have to be logged out to trigger it. Fixing now.

**Comment by jeffklassen** [comment]
Done!
