### ISSUE TITLE
Update Group Error

### ISSUE THREAD

**Issue by BKreisel** [MosaicGroups/mosaic-groups#176]
<img width="962" alt="screen shot 2017-05-19 at 8 28 48 am" src="https://cloud.githubusercontent.com/assets/1513073/26247810/915d688e-3c6d-11e7-879f-7f800d0d41c8.png">

When opening the "manage" link on the groupsList page for the current couples group. I had previously used the "add member" link under the same page to add an additional user

**Comment by jeffklassen** [comment]
It looks like a user object was somehow created, but without a firstName, or any other details:

<img width="391" alt="screen shot 2017-05-19 at 14 48 17" src="https://cloud.githubusercontent.com/assets/7376576/26248584/4373e838-3ca3-11e7-8984-5f3f2407ff78.png">

**Comment by jeffklassen** [comment]
@BKreisel want to take this one? I think the root issue is how the user got partially created

**Comment by BKreisel** [comment]
Partially addressed in  #183.
