### ISSUE TITLE
Joining a group

### ISSUE THREAD

**Issue by pblair12** [MosaicGroups/mosaic-groups#177]
I tried to join this group
![image](https://cloud.githubusercontent.com/assets/1343556/26272621/3362faf4-3ceb-11e7-9946-61906169725a.png)

1) I understand it is a group for 'couples' but it asks me for my 'spouse's name/contact'... maybe it should be updated to 'married couples' or don't use the word 'spouse' since that implies you are married and this is just a group for couples.

2) When I entered fake data for my spouse I got the error "There was an error joining this group" but I don't get any further information and my spouse's contact info is erased while mine stays on the screen.  This might be more than 1 bug.

**Comment by jeffklassen** [comment]
Great find!

**Comment by jeffklassen** [comment]
@pblair12 this had to do with lack of validation for fields on the group-edit page. This was allowing bad data to get into the database. Then when a user tried to join, if there was bad data in the database, the group save operation would fail validation.
