### ISSUE TITLE
Next Semester Msg is on but I can still join groups

### ISSUE THREAD

**Issue by pblair12** [MosaicGroups/mosaic-groups#178]
When I log in and turn on the Next Semester Message then I use another browser to view the page as a user who is not logged in... that user sees the Next Semester Message (good) but is still able to join groups (bad??)

Here is the view from the user who is not logged in
![image](https://cloud.githubusercontent.com/assets/1343556/26272640/f54012ba-3ceb-11e7-904b-49bb91838a5f.png)

**Comment by jeffklassen** [comment]
@pblair12  great find!

**Comment by jeffklassen** [comment]
Closed!

**Comment by jeffklassen** [comment]
See #186
