### ISSUE TITLE
Preferred Method of Contact 

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#188]
The column "Prefers" doesn't show how a member would prefer to be contacted. It shows "approved" or "pending" 
<img width="928" alt="screen shot 2017-05-24 at 9 57 41 am" src="https://cloud.githubusercontent.com/assets/26365037/26406843/84f994ac-4067-11e7-84e1-2995864932aa.png">

**Comment by jeffklassen** [comment]
@amandawmosaic what group are you looking at? I dont see that.

**Comment by jeffklassen** [comment]
@amandawmosaic Whoa, its doing that for me in Safari!

**Comment by jeffklassen** [comment]
Easy fix! #191
