### ISSUE TITLE
Security Certificate Issues

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#197]
![20170611_084551](https://user-images.githubusercontent.com/26365037/27011932-92a2c62e-4e94-11e7-9cb8-05cc7f4510ec.jpg)
![20170611_084628](https://user-images.githubusercontent.com/26365037/27011935-95711ca2-4e94-11e7-8c63-8ebb9d6e3920.jpg)

**Comment by jeffklassen** [comment]
I fixed this using the instructions here:

https://devcenter.heroku.com/articles/automated-certificate-management
