### ISSUE TITLE
Leaders still receiving error messages

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#209]
When leaders make an edit to their group, and then hit "update group" they receive this error message

![image](https://user-images.githubusercontent.com/26365037/27708512-3a4c6c8a-5ce7-11e7-9e19-1b08f46bb133.png)

**Comment by jeffklassen** [comment]
@amandawmosaic does this happen all the time or just with some groups? I just opened a group, then clicked save and only saw a success message. Can you please share a group where this is happening?

**Comment by amandawmosaic** [comment]
From time to time leaders will attempt to make an edit to their group and when they hit "update group" the receive the error pictured above. It's sporadic and only a handful of leaders.

**Comment by jeffklassen** [comment]
This has been fixed @amandawmosaic !
