### ISSUE TITLE
Text from button overflows well

### ISSUE THREAD

**Issue by jeffklassen** [MosaicGroups/mosaic-groups#228]
The text in the 'Interested in leading a growth group in your home' button overflows the containing well when full screen on my mac:

<img width="378" alt="screen shot 2017-09-09 at 8 09 03 am" src="https://user-images.githubusercontent.com/7376576/30237638-73f13f88-9536-11e7-98be-3e38c7eddf6e.png">

**Comment by BKreisel** [comment]
Good catch @jeffklassen.
