### ISSUE TITLE
Add signup count for 'couples' groups

### ISSUE THREAD

**Issue by jeffklassen** [MosaicGroups/mosaic-groups#3]
From an email from JMO:

One thing I know we'd need to tweak for the future is making it possible for someone to indicate "how many people" they're signing up for.

PROBLEM - People are signing up for "couples" groups but then only one person signs up with their email for the two of them. This quickly adds up and if the group is capped at 15, it in fact could have 30 people since there is no designation to say you're signing up for two. 

VISION - have a site where it easily helps leaders know how many are planning on attending their group. 

SOLUTION - I think the solution is putting something in the "sign up" form along with their name and email that indicates how many people are they signing up for. Perhaps, we can make this available ONLY for groups that are selected as "marriage/couple" groups.

**Comment by jeffklassen** [comment]
Waiting on sample data from the existing prod DB

**Comment by pblair12** [comment]
You should have the ability to export the database now... let me know if it does not work

**Comment by shawalli** [comment]
Optionally, allow an "add email" when signing up for the person to put their spouses email.

**Comment by jeffklassen** [comment]
@amandawmosaic -- Is this something we still want? You did not mention this in your phone call

**Comment by amandawmosaic** [comment]
Basically we have people taking up two spots as a couple, but only one slot is "filled" because only one person signs up.  Would it be possible to make it a required field to put two emails in when someone signs up for a group that's designated for couples?

**Comment by jeffklassen** [comment]
@amandawmosaic Do you think it would be better to make the user to use full name and email and everything for 2 people when they sign up for a group? So basically, two name, email address fields when the group is a couple group?

**Comment by amandawmosaic** [comment]
That's an excellent idea

**Comment by jeffklassen** [comment]
Done!
