### ISSUE TITLE
Refactor the serverside to create a services layer

### ISSUE THREAD

**Issue by pblair12** [MosaicGroups/mosaic-groups#35]
We are missing a services layer in our serverside code.  Lets refactor the app to fix that.

**Comment by jeffklassen** [comment]
I vote we merge the changes I have so far -- the group controller has been completely refactored. What do you think @pblair12 ?

**Comment by pblair12** [comment]
yea man! go for it

**Comment by jeffklassen** [comment]
Merged groups service. Pushing into prod momentarily. I will be on hand to make sure nothing breaks :)

**Comment by jeffklassen** [comment]
Closing this for now. Refactoring maybe continued in the future. We may want to switch everything to promises/async functions.
