### ISSUE TITLE
Send a ping to wake up app long enough to send out reports

### ISSUE THREAD

**Issue by jeffklassen** [MosaicGroups/mosaic-groups#36]
1) figure out timing of reports
2) locate a server that can send a ping a few seconds before the report generation begins.

**Comment by pblair12** [comment]
We don't send the daily reports anymore so this is not necessary.  Just curious.. would it be necessary on AWS?  Does AWS put us to sleep like Heroku does?

**Comment by jeffklassen** [comment]
Nope! no sleep!

**Comment by pblair12** [comment]
niceee
