### ISSUE TITLE
Fix Formatting of the Group Membership Confirmation Email 

### ISSUE THREAD

**Issue by pblair12** [MosaicGroups/mosaic-groups#37]
![image](https://cloud.githubusercontent.com/assets/1343556/12166448/1227cb38-b4f4-11e5-927e-4140321399e8.png)

**Comment by jeffklassen** [comment]
@pblair12 what needs to be changed about the confirmation email?

**Comment by pblair12** [comment]
When a new person is added the group leader gets an email.  Every once in a while group leaders reply to that email thinking it is going to the person who signed up but really it is going back to mosaicgroups@gmail.com.  I think that the email to the leader should say something like "this is an email from MosaicgGroups.com to notify you that you have a new member request to the group <name>.  Please contact them via <their email> to let them know more information"... something like that.

Also when a person registers for too many groups it looks like there is an Error in the system... I think that email could be reworded a bit.

**Comment by BKreisel** [comment]
#59 Added the disclaimer for new members. I'm assuming this doesn't address the "too many groups" error @pblair12  mentioned.

**Comment by jeffklassen** [comment]
Good catch @BKreisel. Im going to close this issue and split that second note @pblair12 out into its own issue.
