### ISSUE TITLE
https for user log in

### ISSUE THREAD

**Issue by jeffklassen** [MosaicGroups/mosaic-groups#4]
Let's configure https for user log in.

I see here: https://devcenter.heroku.com/articles/ssl-endpoint that this costs money. How much?

**Comment by pblair12** [comment]
Ha yes!  Funny thing is that i actually think I had https for login at one point... I just disabled it because I didn't want to pay for it.  In reality Mosaic will pay for it :)

**Comment by jeffklassen** [comment]
Do you know what the cost is? If you get me set up with heroku, I’ll work with Jmo to get that set up. 

Jeff Klassen
Software Engineer

Email  jeff.klassen@siginttech.com

**Comment by pblair12** [comment]
I remember it was a very low monthly cost... not much at all... < $10 per month for sure, maybe even < $5

**Comment by pblair12** [comment]
Jeff is crushing this right now ;)  Go @jeffklassen Go!

**Comment by jeffklassen** [comment]
Done! Thanks to @pblair12
