### ISSUE TITLE
Add "Interested in Babysitting/Hosting/Leading" Link

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#51]

**Comment by jeffklassen** [comment]
Hey - what text would you like for each of the links? Also, on the home page in the left hand tab is okay?

**Comment by amandawmosaic** [comment]
Host: Hey! Not ready to lead a group, but you've got space to host one? Awesome! Let us know by emailing here! [link to jessica@mosaicchristian.org]
Lead: Hey! Interested in leading a growth group? Awesome! Fill out the application here [link to www.mosaicchristian.org/leadagroup] We're looking forward to hearing from you!
Childcare: Hey! Looking to make some extra cash on the side? Join our team of background check babysitters, and help make it possible for parents to connect each and every semester! [link to jessica@mosaicchristian.org]

**Comment by jeffklassen** [comment]
@amandawmosaic I've put these links in the left hand bar (not available in production yet):
<img width="1390" alt="screen shot 2017-03-27 at 10 08 27 am" src="https://cloud.githubusercontent.com/assets/7376576/24346623/6f66df6a-12d5-11e7-861a-68d1a842cd99.png">

I think that looks a little squished. Should we move it somewhere or reduce the amount of text?

**Comment by amandawmosaic** [comment]
I was thinking that "Host" "Lead" "Childcare" would be links that would be clicked on to open up small windows with the message and link. Make sense?

**Comment by jeffklassen** [comment]
Ah, that's helpful. Im not a designer, but what do you think about this?

<img width="1090" alt="screen shot 2017-03-28 at 9 53 19 am" src="https://cloud.githubusercontent.com/assets/7376576/24394520/9377f8b8-139c-11e7-89ce-37e7a7cf42d1.png">

**Comment by jeffklassen** [comment]
Should we move those buttons to the top?

**Comment by amandawmosaic** [comment]
That looks perfect.
I like where the buttons are now, but in all honesty I don't know what you mean by "simple links"

**Comment by jeffklassen** [comment]
Thats great! Let's call this one closed and I'll get it merged!

**Comment by BKreisel** [comment]
Merged #96
