### ISSUE TITLE
Notification Before Posting Group

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#65]
Notification would say "Hey! Thanks so much for entering your group's information into the website! Before the website goes live are there any edits you would like to make to ensure your group's description is free of spelling and grammatical errors?"

**Comment by jeffklassen** [comment]
@amandawmosaic do you view this as a pop-up that users must click either 'ok' to continue or 'make changes' to go back and make changes?

Or is this a message that is displayed right above the 'Create Group' button?

**Comment by amandawmosaic** [comment]
I like the idea of a pop up- that's perfect

**Comment by BKreisel** [comment]
Implemented in #109.

**Comment by jeffklassen** [comment]
Looks good to me!
