### ISSUE TITLE
Preferred Method of Contact

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#66]
When people sign up they input their phone, email and preferred method contact.

**Comment by jeffklassen** [comment]
@BKreisel I see you merged this. Is it safe to close this issue?

**Comment by BKreisel** [comment]
@jeffklassen. Almost. I made a strange kind of mess doing a rebase. Check to see if #91 solves this.

**Comment by jeffklassen** [comment]
@BKreisel - please see my last comment (with screenshots) in the pull request I closed (but shouldnt have): https://github.com/MosaicGroups/mosaic-groups/pull/91

**Comment by jeffklassen** [comment]
@BKreisel  Also -- the UI looks great on this, and it looks like things are being saved to the DB. I think we might also want to add a line to the notification email that is sent to the group leader to say:

Preferred Contact Method: <email|phone>.

@amandawmosaic Do we also want to display this message on the manage group page?

**Comment by jeffklassen** [comment]
@BKreisel it looks like for the student contact for Little Bobby Jones, there was no preferredContactVia property which was breaking the test, since this is marked as a required field. I've added that field to the test file and committed.

This is in response to your comment on #91 -- since we will have to make another pull request to merge, we should probably have this convo here.

**Comment by BKreisel** [comment]
@jeffklassen, that is strange. The preferContactVia property should have been added to the tests during  6f14f44 on line 78. I'm trying to comb through the commits and see where the disconnect occurred.

**Comment by jeffklassen** [comment]
@amandawmosaic, @BKreisel has done this. 

In the ticket, you did not mention how you want the application to act on this data. I think that we probably want to do this.

**Comment by amandawmosaic** [comment]
I'm not sure I understand your question. Are you asking, how do I want leaders to be able to access this info? I'd like it to appear alongside the member's contact info when the leader manages their group. It would also email emailed out when the site notifies a leader that someone has signed up for their group.

**Comment by BKreisel** [comment]
Yea. This can be done.

**Comment by BKreisel** [comment]
Implemented in #104

**Comment by jeffklassen** [comment]
This looks great to me! Closing
