### ISSUE TITLE
Capture Campus and Gender

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#74]
When people sign up for groups, the form asks them to specify their campus [Which campus do you regularly attend] and Gender [Male or Female]

**Comment by jeffklassen** [comment]
Where do we want to display this elsewhere on the site?

**Comment by jeffklassen** [comment]
@amandawmosaic Where do we want to display this elsewhere on the site? Do we want this info in the 'view group' page? Also the email sent to the leader?

**Comment by amandawmosaic** [comment]
I want it in the view group page, email info to leader, and in the groups report.
