### ISSUE TITLE
Reword Title 

### ISSUE THREAD

**Issue by amandawmosaic** [MosaicGroups/mosaic-groups#88]
Instead of "Join a Mosaic Growth Group Summer 2017 Growth Group" I'd like it to read "Join a Mosaic Growth Group" that way it doesn't need to be changed every semester. 

Is there a way to do this and have the semester still cataloged with its corresponding season and year for archival purposes?

**Comment by jeffklassen** [comment]
Yes. I can change the text to say that. The semester cataloging will still
happen. Make sure you continue to give good names to semesters (like Summer
2017), even though you wont see the names for the time being.

We will work to expose old groups to you in the future.
